server:
  port: 8001
spring:
  #配置sleush + zipkin
  zipkin:
    bash-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  application:
    name: cloud-provider-payment  # 入驻eureka的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    druid:
      url: jdbc:mysql://localhost:3306/house?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springCloud.pojo

eureka:
  #instance:
  #  hostname: provider8001
  client:
    register-with-eureka: true  #表示将自己注册进eureka 服务注册中心
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 注册的eureka 服务器地址
  instance:
    instance-id: payment8001    #修改eureka显示的访问名字
    prefer-ip-address: true     #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 1 # eureka 客户端向服务端发送心跳的间隔时间 默认30秒
    lease-expiration-duration-in-seconds: 2 #eureka服务端在收到最后一次心跳后的等待时间，超时将剔除服务 默认90(前提是服务端关闭了自我保护机制)