server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment-hystrix
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true # true 表示想注册中心注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
