
spring:
  application:
    name: nacos10000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 10001
management:
  endpoints:
    web:
      exposure:
        exclude: "*"